name: Android 14 Remote Emulator

on:
  workflow_dispatch:


jobs:

  android:

    runs-on: ubuntu-latest


    steps:

      - name: Checkout repository
        uses: actions/checkout@v5


      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: zulu
          java-version: 17


      - name: Install Android SDK

        run: |

          yes | sdkmanager --licenses || true

          sdkmanager \
            "platform-tools" \
            "emulator" \
            "platforms;android-34" \
            "system-images;android-34;google_apis;x86_64"



      - name: Enable KVM

        run: |

          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm.rules

          sudo udevadm control --reload-rules

          sudo udevadm trigger



      - name: Create Android 14 Emulator

        run: |

          echo "no" | avdmanager create avd \
            -n android14 \
            -k "system-images;android-34;google_apis;x86_64" \
            --force



      - name: Setup Tailscale

        uses: tailscale/github-action@v4

        with:

          authkey: ${{ secrets.TAILSCALE_AUTHKEY }}

          hostname: github-android14



      - name: Check Tailscale

        run: |

          sleep 5

          echo "Tailscale status"

          sudo tailscale status


          echo "Tailscale IP"

          sudo tailscale ip -4



      - name: Start Android Emulator

        run: |

          echo "Starting Android 14 emulator"


          emulator \
            -avd android14 \
            -no-window \
            -no-audio \
            -gpu swiftshader_indirect \
            -no-boot-anim \
            -no-snapshot \
            -no-snapshot-save \
            -wipe-data \
            > emulator.log 2>&1 &



          echo "Starting ADB"

          adb start-server



          echo "Waiting for emulator device"


          adb wait-for-device



          echo "Waiting for Android boot"


          COUNT=0

          until adb shell getprop sys.boot_completed | grep -m 1 "1"
          do

            sleep 5

            COUNT=$((COUNT+1))


            if [ $COUNT -gt 60 ]
            then
              echo "Android boot timeout"

              cat emulator.log

              exit 1

            fi

          done



          echo "Android started"



          echo "ADB devices"

          adb devices



          echo "Enable TCP ADB"


          adb tcpip 5555



          sleep 5



          IP=$(sudo tailscale ip -4)



          echo ""

          echo "===================================="

          echo " CONNECT FROM YOUR PC USING:"

          echo ""

          echo "adb connect ${IP}:5555"

          echo ""

          echo "===================================="



          echo "Keeping emulator alive for 6 hours"



          sleep 21600
